(()=>{
 const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
 const header=q('#header'),progress=q('#progress'),hero=q('#heroArt'),brandLogo=q('#brandLogo');
 const coarse=matchMedia('(hover:none) and (pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 const heroHQ=window.MJ_ASSETS?.['@@A00@@']||'';
 if(heroHQ){hero.style.backgroundImage=`url("${heroHQ}")`;hero.style.backgroundSize='cover';hero.style.backgroundPosition=coarse?'center 42%':'center';}
 else {hero.style.backgroundImage='url("./assets/images/photo-01.avif?v=56")';hero.style.backgroundSize='cover';hero.style.backgroundPosition='center'}
 if(window.MJ?.LOGO) brandLogo.src=window.MJ.LOGO; else {brandLogo.src='data:image/gif;base64,R0lGODlhAQABAAAAACw=';brandLogo.style.opacity='.25'}
 let ticking=false;
 function frame(){ticking=false;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);progress.style.width=(scrollY/max*100)+'%';header.classList.toggle('scrolled',scrollY>18);if(!coarse&&!reduced&&hero){const y=Math.max(-12,Math.min(0,-scrollY*.025));hero.style.backgroundPosition=`center calc(50% + ${y}px)`}}
 function tick(){if(!ticking){ticking=true;requestAnimationFrame(frame)}}
 addEventListener('scroll',tick,{passive:true});addEventListener('resize',tick,{passive:true});tick();
 const io='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{rootMargin:'0px 0px -7% 0px',threshold:.07}):null;qa('.reveal').forEach(el=>io?io.observe(el):el.classList.add('visible'));
 const salonPos={'photo-01':['0%','0%'],'photo-02':['33.333%','0%'],'photo-04':['66.666%','0%'],'photo-05':['100%','0%'],'photo-06':['0%','100%'],'photo-07':['33.333%','100%'],'photo-08':['66.666%','100%']};
 const teamPos={'photo-09':['0%','0%'],'photo-10':['50%','0%'],'photo-11':['100%','0%'],'photo-12':['0%','100%'],'photo-13':['50%','100%'],'photo-14':['100%','100%']};
 const fallback={'photo-01':'./assets/images/photo-01.avif?v=56','photo-02':'./assets/images/photo-02.avif?v=56','photo-04':'./assets/images/photo-04.avif?v=56','photo-05':'./assets/images/photo-05.avif?v=56','photo-06':'./assets/images/photo-06.avif?v=56','photo-07':'./assets/images/photo-07.avif?v=56','photo-08':'./assets/images/photo-08.avif?v=56'};
 qa('[data-salon]').forEach(el=>{el.style.backgroundImage=`url("${fallback[el.dataset.salon]}")`;el.style.backgroundSize='cover';el.style.backgroundPosition='center'});
 function hydrateSalon(){qa('[data-salon]').forEach(el=>{const p=salonPos[el.dataset.salon];if(!p)return;el.classList.add('atlas-salon');el.style.setProperty('--ax',p[0]);el.style.setProperty('--ay',p[1])})}
 function hydrateTeam(){qa('[data-team]').forEach(el=>{const p=teamPos[el.dataset.team];if(!p)return;el.classList.add('atlas-team');el.style.setProperty('--ax',p[0]);el.style.setProperty('--ay',p[1])})}
 addEventListener('mj-salon-ready',hydrateSalon);addEventListener('mj-team-ready',hydrateTeam);
 if(getComputedStyle(document.documentElement).getPropertyValue('--salon-atlas').trim())hydrateSalon();if(getComputedStyle(document.documentElement).getPropertyValue('--team-atlas').trim())hydrateTeam();
 const services=['Hair Care','Skin Care','Nail Care','Package'],times=['1:00 PM','4:00 PM','7:30 PM','9:00 PM'],state={service:'Hair Care',time:'7:30 PM',name:'',phone:''};let step=0;const booking=q('#booking'),stepBtns=qa('[data-step]');
 function render(target=booking){stepBtns.forEach((b,i)=>b.classList.toggle('active',i===step));if(step===0)target.innerHTML=`<h3>اختر الخدمة</h3><div class="opts">${services.map(x=>`<button class="opt ${state.service===x?'sel':''}" data-service="${x}">${x}</button>`).join('')}</div><div class="nextrow"><button class="nextbtn" data-next>Continue</button></div>`;if(step===1)target.innerHTML=`<h3>اختر الوقت</h3><div class="opts">${times.map(x=>`<button class="opt ${state.time===x?'sel':''}" data-time="${x}">${x}</button>`).join('')}</div><div class="nextrow"><button class="nextbtn" data-next>Continue</button></div>`;if(step===2)target.innerHTML=`<h3>بياناتك</h3><div class="form"><input id="bookingName" autocomplete="name" value="${state.name}" placeholder="الاسم"><input id="bookingPhone" inputmode="tel" autocomplete="tel" value="${state.phone}" placeholder="رقم الهاتف"></div><div class="summary"><strong>${state.service}</strong><br>${state.time} · MJ Hair Salon</div><div class="nextrow"><button class="nextbtn" data-done>Confirm demo booking</button></div>`;qa('[data-service]',target).forEach(b=>b.onclick=()=>{state.service=b.dataset.service;render(target)});qa('[data-time]',target).forEach(b=>b.onclick=()=>{state.time=b.dataset.time;render(target)});q('[data-next]',target)?.addEventListener('click',()=>{step=Math.min(2,step+1);render(target)});q('[data-done]',target)?.addEventListener('click',()=>{const n=q('#bookingName',target),p=q('#bookingPhone',target);state.name=n?.value.trim()||'';state.phone=p?.value.trim()||'';const bad=!state.name?n:state.phone.replace(/\D/g,'').length<7?p:null;if(bad){bad.classList.add('input-error');bad.focus();return}target.innerHTML=`<div class="summary"><strong>Reserved.</strong><br>${state.service} · ${state.time}<br>${state.name} · ${state.phone}<br><small>Demo confirmation only — no live appointment was submitted.</small></div>`})}
 stepBtns.forEach((b,i)=>b.onclick=()=>{step=i;render()});render();
 const modal=q('#modal'),mc=q('#modalContent');function openModal(){step=0;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';render(mc)}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}qa('[data-book]').forEach(b=>b.addEventListener('click',openModal));qa('[data-close]').forEach(b=>b.addEventListener('click',closeModal));addEventListener('keydown',e=>e.key==='Escape'&&closeModal());
})();
