(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,ease=t=>1-Math.pow(1-clamp(t),3);
const coarse=matchMedia('(hover:none) and (pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
const header=$('#header'),bar=$('#progressBar'),heroArt=$('#heroArt'),heroContent=$('#heroContent'),metaA=$('#metaA'),metaB=$('#metaB'),heroLines=$$('.hero-lines i'),exp=$('#experience'),scenes=$$('[data-scene]'),sceneIndex=$('#sceneIndex');
if(window.MJ?.LOGO){const logo=$('#brandLogo');logo.src=window.MJ.LOGO}else{const logo=$('#brandLogo');if(logo){logo.alt='MJ';logo.style.opacity='.2'}}
const heroHQ=window.MJ_ASSETS?.['@@A00@@']||'';if(heroHQ&&heroArt){heroArt.style.backgroundImage=`url("${heroHQ}")`;heroArt.style.backgroundSize='cover';heroArt.style.backgroundPosition=coarse?'50% 42%':'center 48%'}
const teamPos=[['0%','0%'],['50%','0%'],['100%','0%'],['0%','100%'],['50%','100%'],['100%','100%']];function hydrateTeam(){if(!getComputedStyle(document.documentElement).getPropertyValue('--team-atlas').trim())return;$$('[data-team]').forEach(el=>{const p=teamPos[Number(el.dataset.team)-1];if(!p)return;el.classList.add('atlas-team');el.style.setProperty('--tx',p[0]);el.style.setProperty('--ty',p[1])})}addEventListener('mj-team-ready',hydrateTeam);queueMicrotask(hydrateTeam);
let ticking=false,mx=0,my=0,tx=0,ty=0;const progressOf=el=>{if(!el)return 0;const r=el.getBoundingClientRect(),travel=Math.max(1,el.offsetHeight-innerHeight);return clamp(-r.top/travel)};
function renderScroll(){ticking=false;const doc=Math.max(1,document.documentElement.scrollHeight-innerHeight);if(bar)bar.style.width=(scrollY/doc*100)+'%';header?.classList.toggle('scrolled',scrollY>24);const hp=progressOf(document.querySelector('.hero-scroll')),out=ease(clamp((hp-.58)/.40)),imageShift=coarse?0:hp*22;if(heroArt&&!reduced)heroArt.style.transform=`translate3d(0,${-imageShift}px,0) scale(${1.006+hp*.022})`;if(heroContent&&!reduced){heroContent.style.transform=`translate3d(${coarse?0:mx*7}px,${-hp*56+my*4}px,0)`;heroContent.style.opacity=String(1-out*.82)}if(metaA&&!coarse&&!reduced)metaA.style.transform=`translate3d(${mx*16}px,${hp*24+my*8}px,0)`;if(metaB&&!coarse&&!reduced)metaB.style.transform=`translate3d(${mx*10}px,${-hp*18+my*6}px,0)`;if(!reduced)heroLines.forEach((l,i)=>{const dir=i===1?-1:1;l.style.translate=`${dir*(hp*34)+(coarse?0:mx*(5+i*2))}px ${-hp*(5+i*4)}px`});const ep=progressOf(exp),s=ep*3;let active=0;scenes.forEach((el,i)=>{const local=s-i,enter=ease(clamp((local+.05)/.58)),exit=ease(clamp((local-.72)/.38)),opacity=clamp(enter*(1-exit));if(opacity>.4)active=i;if(reduced){el.style.opacity=i===Math.min(2,Math.floor(ep*3))?'1':'0';el.style.transform='none';return}const x=lerp(74,0,enter)-exit*54,y=lerp(34,0,enter)-exit*22,z=lerp(-150,0,enter)-exit*80,ry=lerp(-7,0,enter)+exit*4,sc=.93+enter*.07-exit*.025;el.style.opacity=String(opacity);el.style.transform=`translate3d(${x}px,${y}px,${z}px) rotateY(${ry}deg) scale(${sc})`;el.style.zIndex=String(10+i)});if(sceneIndex)sceneIndex.textContent='0'+(active+1);window.MJ_SCROLL_STATE={hero:hp,experience:ep,activeScene:active}}
function requestRender(){if(!ticking){ticking=true;requestAnimationFrame(renderScroll)}}addEventListener('scroll',requestRender,{passive:true});addEventListener('resize',requestRender,{passive:true});if(!coarse&&!reduced)addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2;mx=lerp(mx,tx,.55);my=lerp(my,ty,.55);requestRender()},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{rootMargin:'0px 0px -7% 0px',threshold:.06});$$('.reveal').forEach(el=>io.observe(el));if(!coarse&&!reduced)$$('.tilt').forEach(card=>{let rt=0;card.addEventListener('pointermove',e=>{if(rt)return;rt=requestAnimationFrame(()=>{rt=0;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(950px) rotateY(${x*4.5}deg) rotateX(${-y*4.5}deg) translateY(-3px)`})});card.addEventListener('pointerleave',()=>card.style.transform='')});
const state={service:'Hair Care',time:'7:30 PM',name:'',phone:''};let step=0;const booking=$('#booking'),stepBtns=$$('[data-step]'),serviceLabels={'Hair Care':['العناية بالشعر','Cut · Styling · Treatment'],'Skin Care':['العناية بالبشرة','Grooming facial'],'Nail Care':['العناية بالأظافر','Detail care'],'Package':['البكجات','Full grooming package']};
function renderBooking(){stepBtns.forEach((b,i)=>b.classList.toggle('active',i===step));if(!booking)return;if(step===0)booking.innerHTML=`<h3>اختر الخدمة</h3><p>حدد الخدمة التي تريدها.</p><div class="options">${Object.entries(serviceLabels).map(([v,a])=>`<button class="option ${state.service===v?'selected':''}" data-service="${v}"><strong>${a[0]}</strong><small>${a[1]}</small></button>`).join('')}</div><div class="booking-next"><button data-next>متابعة</button></div>`;else if(step===1)booking.innerHTML=`<h3>اختر الوقت</h3><p>الأوقات هنا للعرض التجريبي.</p><div class="times">${['1:00 PM','4:00 PM','7:30 PM','9:00 PM'].map(t=>`<button class="time ${state.time===t?'selected':''}" data-time="${t}">${t}</button>`).join('')}</div><div class="booking-next"><button data-next>متابعة</button></div>`;else booking.innerHTML=`<h3>بياناتك</h3><p>أكمل بيانات الحجز.</p><div class="inputs"><input id="name" autocomplete="name" value="${state.name}" placeholder="الاسم الكامل"><input id="phone" inputmode="tel" autocomplete="tel" value="${state.phone}" placeholder="رقم الهاتف"></div><div class="summary"><b>${serviceLabels[state.service][0]}</b><br>${state.time} · MJ Hair Salon</div><div class="booking-next"><button data-confirm>تأكيد الحجز التجريبي</button></div>`;$$('[data-service]',booking).forEach(b=>b.onclick=()=>{state.service=b.dataset.service;renderBooking()});$$('[data-time]',booking).forEach(b=>b.onclick=()=>{state.time=b.dataset.time;renderBooking()});$('[data-next]',booking)?.addEventListener('click',()=>{step=Math.min(2,step+1);renderBooking()});$('[data-confirm]',booking)?.addEventListener('click',()=>{const n=$('#name',booking),p=$('#phone',booking);state.name=n?.value.trim()||'';state.phone=p?.value.trim()||'';if(!state.name||state.phone.replace(/\D/g,'').length<7){(!state.name?n:p)?.focus();return}booking.innerHTML=`<div class="summary"><b>تم تسجيل الحجز التجريبي.</b><br>${serviceLabels[state.service][0]} · ${state.time}<br>${state.name} · ${state.phone}<br><small>Demo only — لم يتم إنشاء حجز فعلي.</small></div>`})}stepBtns.forEach((b,i)=>b.addEventListener('click',()=>{step=i;renderBooking()}));renderBooking();
const modal=$('#modal');function openModal(service){if(service)state.service=service;modal?.classList.add('open');modal?.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModal(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.style.overflow=''}$$('[data-book]').forEach(b=>b.addEventListener('click',()=>openModal()));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModal));$$('[data-modal-service]').forEach(b=>b.addEventListener('click',()=>{state.service=b.dataset.modalService;closeModal();step=1;renderBooking();document.querySelector('#contact')?.scrollIntoView({behavior:'smooth'})}));addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});requestRender();
})();