(()=>{
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const A=window.MJ_ASSETS||{},heroAsset=A['@@A00@@']||'';const heroMedia=q('#heroMedia');if(heroAsset)heroMedia.style.backgroundImage=`url(${heroAsset})`;
const headLogo=q('#headLogo'),heroLogo=q('#heroLogo');if(window.MJ?.LOGO){headLogo.src=window.MJ.LOGO;heroLogo.src=window.MJ.LOGO}else{headLogo.style.display='none';heroLogo.style.display='none'}
qa('.avatar:not(.initial)').forEach(x=>{if(window.MJ?.TEAM)x.style.backgroundImage=`url(${window.MJ.TEAM})`});
const coarse=matchMedia('(hover:none) and (pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
async function b64Image(path){const r=await fetch(path,{cache:'force-cache'});if(!r.ok)throw new Error('asset '+r.status);const s=(await r.text()).replace(/\s+/g,'');const bin=atob(s),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return URL.createObjectURL(new Blob([out],{type:'image/avif'}))}
const serviceImgs=qa('.service img[data-photo]');let localLoaded=false;async function loadLocalPhotos(){if(localLoaded)return;localLoaded=true;const files=['./assets/images/photo-05.b64?v=53','./assets/images/photo-06.b64?v=53','./assets/images/photo-07.b64?v=53'];try{const urls=await Promise.all(files.map(b64Image));serviceImgs.forEach((img,i)=>{img.onload=()=>img.classList.add('loaded');img.onerror=()=>{if(heroAsset){img.src=heroAsset;img.classList.add('loaded')}};img.src=urls[i%urls.length]})}catch(e){serviceImgs.forEach(img=>{if(heroAsset){img.src=heroAsset;img.classList.add('loaded')}})}}
const services=q('#services');if(services&&'IntersectionObserver'in window){const sio=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){loadLocalPhotos();sio.disconnect()}},{rootMargin:'700px 0px'});sio.observe(services)}else loadLocalPhotos();
let tx=0,ty=0,mx=0,my=0,px=innerWidth/2,py=innerHeight/2;if(!coarse&&!reduced)addEventListener('pointermove',e=>{px=e.clientX;py=e.clientY;tx=e.clientX/innerWidth*2-1;ty=e.clientY/innerHeight*2-1},{passive:true});
const header=q('#header'),prog=q('#prog'),heroScroll=q('.hero-scroll'),heroCopy=q('#heroCopy'),heroSide=q('#heroSide'),exp=q('.experience-scroll'),scenes=qa('.scene'),markers=qa('.experience-marker'),rails=qa('.rail');
function secP(el){const r=el.getBoundingClientRect(),d=Math.max(1,el.offsetHeight-innerHeight);return clamp(-r.top/d)}
let lastFrame=0;function tick(now=0){if(document.hidden)return requestAnimationFrame(tick);if(coarse&&now-lastFrame<32)return requestAnimationFrame(tick);lastFrame=now;mx=lerp(mx,tx,.065);my=lerp(my,ty,.065);const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),pp=scrollY/max;prog.style.width=pp*100+'%';header.classList.toggle('scrolled',scrollY>24);
if(!reduced){const hp=secP(heroScroll),out=clamp((hp-.67)/.28);heroMedia.style.transform=`scale(${1+hp*.065}) translate3d(${mx*9}px,${-hp*28+my*6}px,0)`;heroCopy.style.transform=`translate3d(${mx*15}px,${-hp*40+my*10}px,0) scale(${1+hp*.018})`;heroCopy.style.opacity=1-out*.92;heroCopy.style.filter=`blur(${out*7}px)`;if(heroSide){heroSide.style.transform=`translate3d(${mx*20}px,${my*12+hp*18}px,0) rotateY(${mx*-2}deg)`;heroSide.style.opacity=1-out*.78}rails.forEach((e,i)=>{const mult=1+i*.28;e.style.translate=`${mx*(16+i*5)}px ${my*(9+i*3)}px`;e.style.scale=`${1+hp*.055*mult}`});qa('.float-chip').forEach((e,i)=>e.style.transform=`translate3d(${mx*(8+i*3)}px,${my*(7+i*2)}px,0)`);
const ep=secP(exp),scaled=ep*3;scenes.forEach((s,i)=>{const l=scaled-i,en=clamp(l/.44),ex=clamp((l-.64)/.36),op=clamp(en*(1-ex));s.style.opacity=op;s.style.filter=`blur(${(1-en)*10+ex*8}px)`;const isCenter=i===2,base=isCenter&&innerWidth>760?'translate(-50%,-50%) ':'';const dx=(i===1?1:-1)*(1-en)*58+mx*10,dy=(1-en)*24-ex*16+my*6;s.style.transform=base+`translate3d(${dx}px,${dy}px,0) scale(${.95+en*.05-ex*.03})`});markers.forEach((m,i)=>{const ph=ep*6.28+i*2.1;m.style.transform=`translate3d(${Math.sin(ph)*26+mx*10}px,${Math.cos(ph*.8)*20+my*9}px,0)`;m.style.opacity=.35+.45*Math.abs(Math.sin(ph*.65))})}
if(!coarse&&!reduced)q('#cursor').style.transform=`translate3d(${px}px,${py}px,0)`;requestAnimationFrame(tick)}requestAnimationFrame(tick);
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.10});qa('.reveal').forEach(x=>io.observe(x));
const dc=q('#dust'),ctx=dc?.getContext('2d');let dots=[];function drs(){if(!dc||!ctx)return;const d=Math.min(devicePixelRatio||1,coarse?1:1.6);dc.width=innerWidth*d;dc.height=innerHeight*d;dc.style.width=innerWidth+'px';dc.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);dots=Array.from({length:reduced?0:coarse?24:Math.min(68,Math.max(38,innerWidth/24|0))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.4+Math.random()*1.05,vx:(Math.random()-.5)*.075,vy:(Math.random()-.5)*.075,a:.05+Math.random()*.17}))}drs();addEventListener('resize',drs,{passive:true});let dustLast=0;(function dd(now=0){if(!ctx||document.hidden)return requestAnimationFrame(dd);if(coarse&&now-dustLast<45)return requestAnimationFrame(dd);dustLast=now;ctx.clearRect(0,0,innerWidth,innerHeight);dots.forEach(d=>{d.x+=d.vx;d.y+=d.vy;if(d.x<0)d.x=innerWidth;if(d.x>innerWidth)d.x=0;if(d.y<0)d.y=innerHeight;if(d.y>innerHeight)d.y=0;ctx.beginPath();ctx.fillStyle=`rgba(233,84,91,${d.a})`;ctx.arc(d.x,d.y,d.r,0,6.283);ctx.fill()});requestAnimationFrame(dd)})();
if(!coarse&&!reduced){qa('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${y*-5}deg) rotateY(${x*7}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
const state={service:'Hair Care',time:'7:30 PM',name:'',phone:''},booking=q('#booking'),steps=qa('.step');let bi=0;function render(){steps.forEach((s,i)=>s.classList.toggle('active',i===bi));if(bi===0)booking.innerHTML=`<h3>اختر الخدمة</h3><div class="opts">${['Hair Care','Skin Care','Nail Care','Package'].map(x=>`<button class="opt ${state.service===x?'sel':''}" data-service="${x}">${x}</button>`).join('')}</div><div class="nextrow"><button class="nextbtn" data-next>Continue</button></div>`;if(bi===1)booking.innerHTML=`<h3>اختر الوقت</h3><div class="opts">${['1:00 PM','4:00 PM','7:30 PM','9:00 PM'].map(x=>`<button class="opt ${state.time===x?'sel':''}" data-time="${x}">${x}</button>`).join('')}</div><div class="nextrow"><button class="nextbtn" data-next>Continue</button></div>`;if(bi===2)booking.innerHTML=`<h3>بياناتك</h3><div class="form"><input id="bookingName" autocomplete="name" value="${state.name}" placeholder="الاسم"><input id="bookingPhone" inputmode="tel" autocomplete="tel" value="${state.phone}" placeholder="رقم الهاتف"></div><div class="summary"><strong>${state.service}</strong><br>${state.time} · MJ Hair Salon</div><div class="nextrow"><button class="nextbtn" data-done>Confirm demo booking</button></div>`;qa('[data-service]',booking).forEach(x=>x.onclick=()=>{state.service=x.dataset.service;render()});qa('[data-time]',booking).forEach(x=>x.onclick=()=>{state.time=x.dataset.time;render()});q('[data-next]',booking)?.addEventListener('click',()=>{bi=Math.min(2,bi+1);render()});q('[data-done]',booking)?.addEventListener('click',()=>{const n=q('#bookingName'),p=q('#bookingPhone');state.name=n?.value.trim()||'';state.phone=p?.value.trim()||'';const bad=!state.name?n:state.phone.replace(/\D/g,'').length<7?p:null;if(bad){bad.classList.add('input-error');bad.focus();return}booking.innerHTML=`<div class="summary"><strong>Reserved.</strong><br>${state.service} · ${state.time}<br>${state.name} · ${state.phone}<br><small>Demo confirmation only — no live appointment was submitted.</small></div>`})}
steps.forEach((x,i)=>x.onclick=()=>{bi=i;render()});render();qa('[data-book]').forEach(x=>x.onclick=()=>{q('#contact').scrollIntoView({behavior:reduced?'auto':'smooth'});bi=0;render()});
})();
