(()=>{
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const A=window.MJ_ASSETS||{},heroAsset=A['@@A00@@']||'';const heroMedia=q('#heroMedia');if(heroAsset)heroMedia.style.backgroundImage=`url(${heroAsset})`;const headLogo=q('#headLogo'),heroLogo=q('#heroLogo');if(window.MJ?.LOGO){headLogo.src=window.MJ.LOGO;heroLogo.src=window.MJ.LOGO}else{headLogo.style.display='none';heroLogo.style.display='none'}
qa('.avatar:not(.initial)').forEach(x=>{if(window.MJ?.TEAM)x.style.backgroundImage=`url(${window.MJ.TEAM})`});
let tx=0,ty=0,mx=0,my=0,px=innerWidth/2,py=innerHeight/2;const coarse=matchMedia('(pointer:coarse)').matches;
if(!coarse)addEventListener('pointermove',e=>{px=e.clientX;py=e.clientY;tx=e.clientX/innerWidth*2-1;ty=e.clientY/innerHeight*2-1},{passive:true});
const header=q('#header'),prog=q('#prog'),heroScroll=q('.hero-scroll'),heroCopy=q('#heroCopy'),heroSide=q('#heroSide'),exp=q('.experience-scroll'),scenes=qa('.scene'),markers=qa('.experience-marker'),rails=qa('.rail');
function secP(el){const r=el.getBoundingClientRect(),d=Math.max(1,el.offsetHeight-innerHeight);return clamp(-r.top/d)}
function tick(){mx=lerp(mx,tx,.065);my=lerp(my,ty,.065);const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),pp=scrollY/max;prog.style.width=pp*100+'%';header.classList.toggle('scrolled',scrollY>24);
const hp=secP(heroScroll),out=clamp((hp-.67)/.28);heroMedia.style.transform=`scale(${1+hp*.07}) translate3d(${mx*9}px,${-hp*30+my*6}px,0)`;heroCopy.style.transform=`translate3d(${mx*15}px,${-hp*42+my*10}px,0) scale(${1+hp*.018})`;heroCopy.style.opacity=1-out*.92;heroCopy.style.filter=`blur(${out*7}px)`;if(heroSide){heroSide.style.transform=`translate3d(${mx*24}px,${my*14+hp*20}px,0) rotateY(${mx*-2.2}deg)`;heroSide.style.opacity=1-out*.78}
rails.forEach((e,i)=>{const mult=1+i*.28;e.style.translate=`${mx*(18+i*6)}px ${my*(10+i*4)}px`;e.style.scale=`${1+hp*.06*mult}`});qa('.float-chip').forEach((e,i)=>e.style.transform=`translate3d(${mx*(9+i*3)}px,${my*(8+i*2)}px,0)`);
const ep=secP(exp),scaled=ep*3;scenes.forEach((s,i)=>{const l=scaled-i,en=clamp(l/.44),ex=clamp((l-.64)/.36),op=clamp(en*(1-ex));s.style.opacity=op;s.style.filter=`blur(${(1-en)*10+ex*8}px)`;const isCenter=i===2,base=isCenter&&innerWidth>760?'translate(-50%,-50%) ':'';const dx=(i===1?1:-1)*(1-en)*58+mx*11,dy=(1-en)*24-ex*16+my*7;s.style.transform=base+`translate3d(${dx}px,${dy}px,0) scale(${.95+en*.05-ex*.03})`});markers.forEach((m,i)=>{const ph=ep*6.28+i*2.1;m.style.transform=`translate3d(${Math.sin(ph)*28+mx*12}px,${Math.cos(ph*.8)*21+my*10}px,0)`;m.style.opacity=.35+.45*Math.abs(Math.sin(ph*.65))});
if(!coarse)q('#cursor').style.transform=`translate3d(${px}px,${py}px,0)`;requestAnimationFrame(tick)}requestAnimationFrame(tick);
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});qa('.reveal').forEach(x=>io.observe(x));
const dc=q('#dust'),ctx=dc.getContext('2d');let dots=[];function drs(){const d=Math.min(devicePixelRatio||1,coarse?1.25:1.7);dc.width=innerWidth*d;dc.height=innerHeight*d;dc.style.width=innerWidth+'px';dc.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);dots=Array.from({length:coarse?38:Math.min(76,Math.max(42,innerWidth/22|0))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.4+Math.random()*1.1,vx:(Math.random()-.5)*.08,vy:(Math.random()-.5)*.08,a:.06+Math.random()*.20}))}drs();addEventListener('resize',drs);(function dd(){ctx.clearRect(0,0,innerWidth,innerHeight);dots.forEach(d=>{d.x+=d.vx;d.y+=d.vy;if(d.x<0)d.x=innerWidth;if(d.x>innerWidth)d.x=0;if(d.y<0)d.y=innerHeight;if(d.y>innerHeight)d.y=0;ctx.beginPath();ctx.fillStyle=`rgba(233,84,91,${d.a})`;ctx.arc(d.x,d.y,d.r,0,6.283);ctx.fill()});requestAnimationFrame(dd)})();
if(!coarse){qa('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${y*-5}deg) rotateY(${x*7}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})};
const state={service:'Hair Care',time:'7:30 PM'},booking=q('#booking'),steps=qa('.step');let bi=0;function render(){steps.forEach((s,i)=>s.classList.toggle('active',i===bi));if(bi===0)booking.innerHTML=`<h3>اختر الخدمة</h3><div class="opts">${['Hair Care','Skin Care','Nail Care','Package'].map(x=>`<button class="opt ${state.service===x?'sel':''}" data-service="${x}">${x}</button>`).join('')}</div><div class="nextrow"><button class="nextbtn" data-next>Continue</button></div>`;if(bi===1)booking.innerHTML=`<h3>اختر الوقت</h3><div class="opts">${['1:00 PM','4:00 PM','7:30 PM','9:00 PM'].map(x=>`<button class="opt ${state.time===x?'sel':''}" data-time="${x}">${x}</button>`).join('')}</div><div class="nextrow"><button class="nextbtn" data-next>Continue</button></div>`;if(bi===2)booking.innerHTML=`<h3>بياناتك</h3><div class="form"><input placeholder="الاسم"><input placeholder="رقم الهاتف"></div><div class="summary"><strong>${state.service}</strong><br>${state.time} · MJ Hair Salon</div><div class="nextrow"><button class="nextbtn" data-done>Confirm demo booking</button></div>`;qa('[data-service]',booking).forEach(x=>x.onclick=()=>{state.service=x.dataset.service;render()});qa('[data-time]',booking).forEach(x=>x.onclick=()=>{state.time=x.dataset.time;render()});q('[data-next]',booking)?.addEventListener('click',()=>{bi=Math.min(2,bi+1);render()});q('[data-done]',booking)?.addEventListener('click',()=>booking.innerHTML='<div class="summary"><strong>Reserved.</strong><br>Demo confirmation only — no live appointment was submitted.</div>')}
steps.forEach((x,i)=>x.onclick=()=>{bi=i;render()});render();qa('[data-book]').forEach(x=>x.onclick=()=>{q('#contact').scrollIntoView({behavior:'smooth'});bi=0;render()});
})();