(()=>{
 const c=document.getElementById('gl'),reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,coarse=matchMedia('(hover:none) and (pointer:coarse)').matches;if(!c||reduced)return;
 const g=c.getContext('webgl',{alpha:true,antialias:false,powerPreference:'high-performance',premultipliedAlpha:true});if(!g)return;
 const vs=`attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`;
 const fs=`precision mediump float;uniform vec2 r;uniform float t,s;float seg(vec2 p,vec2 a,vec2 b){vec2 pa=p-a,ba=b-a;float h=clamp(dot(pa,ba)/dot(ba,ba),0.,1.);return length(pa-ba*h);}void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/r.y;float T=t*.12;vec3 col=vec3(.008,.012,.02);for(int i=0;i<3;i++){float f=float(i);vec2 cc=vec2(sin(T+f*2.1)*.62,cos(T*.8+f*1.6)*.42);float d=length(uv-cc);vec3 tone=i==1?vec3(.72,.05,.08):vec3(.025,.12,.24);col+=tone*exp(-d*d*(5.0+f))*0.13;}for(int i=0;i<6;i++){float f=float(i),ph=f*.82+s*4.;vec2 a=vec2(-1.3,sin(T+ph)*.34+f*.027-.16);vec2 b=vec2(1.3,sin(T*1.15+ph+1.1)*.30-f*.018);float d=seg(uv,a,b);float rb=smoothstep(.024,.010,d);vec3 tone=mix(vec3(.025,.10,.22),vec3(.78,.06,.10),step(3.0,f));col=mix(col,tone,rb*(.08+.018*f));}float vig=smoothstep(1.4,.2,length(uv*vec2(1.,.78)));col*=vig;gl_FragColor=vec4(col,.82);}`;
 function sh(type,src){const x=g.createShader(type);g.shaderSource(x,src);g.compileShader(x);return x}const pr=g.createProgram();g.attachShader(pr,sh(g.VERTEX_SHADER,vs));g.attachShader(pr,sh(g.FRAGMENT_SHADER,fs));g.linkProgram(pr);g.useProgram(pr);const b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),g.STATIC_DRAW);const loc=g.getAttribLocation(pr,'p');g.enableVertexAttribArray(loc);g.vertexAttribPointer(loc,2,g.FLOAT,false,0,0);const ur=g.getUniformLocation(pr,'r'),ut=g.getUniformLocation(pr,'t'),us=g.getUniformLocation(pr,'s');
 function resize(){const scale=coarse?.55:Math.min(devicePixelRatio||1,1.25);c.width=Math.max(1,Math.round(innerWidth*scale));c.height=Math.max(1,Math.round(innerHeight*scale));c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';g.viewport(0,0,c.width,c.height)}resize();addEventListener('resize',resize,{passive:true});
 let active=true,last=0;document.addEventListener('visibilitychange',()=>active=!document.hidden);function draw(now){if(!active)return requestAnimationFrame(draw);if(coarse&&now-last<16)return requestAnimationFrame(draw);last=now;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);g.uniform2f(ur,c.width,c.height);g.uniform1f(ut,now*.001);g.uniform1f(us,scrollY/max);g.drawArrays(g.TRIANGLES,0,6);requestAnimationFrame(draw)}requestAnimationFrame(draw);
})();
