(()=>{
const canvas=document.getElementById('gl'),gl=canvas.getContext('webgl2',{alpha:true,antialias:true,premultipliedAlpha:true});if(!gl){canvas.style.display='none';return}const coarse=matchMedia('(pointer:coarse)').matches;
const VS=`#version 300 es
precision highp float;in vec2 aUV;uniform mat4 uProj,uView;uniform float uTime,uScroll,uId,uPhase;uniform vec2 uMouse;out vec3 vN;out float vEdge,vZ;
mat3 ry(float a){float c=cos(a),s=sin(a);return mat3(c,0.,s,0.,1.,0.,-s,0.,c);}mat3 rx(float a){float c=cos(a),s=sin(a);return mat3(1.,0.,0.,0.,c,-s,0.,s,c);}mat3 rz(float a){float c=cos(a),s=sin(a);return mat3(c,-s,0.,s,c,0.,0.,0.,1.);}vec3 rp(vec2 uv){float u=uv.x,v=uv.y-.5;float amp=.22+.24*sin(uScroll*3.14159);float x=(u-.5)*7.8;float y=sin(u*4.6+uPhase+uTime*.42)*amp+sin(u*10.3+uPhase*1.3-uTime*.20)*.07;float z=cos(u*3.0+uPhase+uTime*.18)*(.33+.19*sin(uScroll*3.14159));float tw=u*6.6+uPhase+uTime*.26+uScroll*3.2;float w=.15+.04*sin(u*6.+uPhase);y+=v*w*cos(tw);z+=v*w*sin(tw);return vec3(x,y,z);}void main(){vec3 p=rp(aUV);p.y+=(uId-2.5)*.30;p.z+=(uId-2.5)*.055;float ang=uScroll*1.25+(uId-2.5)*.04+uMouse.x*.22;p=ry(ang)*rz((uId-2.5)*.06+uScroll*.05)*p;p=rx(uMouse.y*.12)*p;p.z+=smoothstep(.0,.32,uScroll)*.36;vec3 pa=rp(vec2(min(aUV.x+.006,1.),aUV.y)),pb=rp(vec2(aUV.x,min(aUV.y+.02,1.)));vec3 n=normalize(cross(pb-p,pa-p));vN=normalize(ry(ang)*n);vEdge=abs(aUV.y-.5)*2.;vZ=p.z;gl_Position=uProj*uView*vec4(p,1.);}`;
const FS=`#version 300 es
precision highp float;in vec3 vN;in float vEdge,vZ;uniform float uId,uScroll,uTime;out vec4 outColor;void main(){vec3 navy=vec3(.025,.12,.24),blue=vec3(.12,.36,.62),red=vec3(.86,.045,.08),silver=vec3(.74,.80,.86);float fres=pow(1.-abs(dot(normalize(vN),vec3(0.,0.,1.))),2.1);float stripe=.5+.5*sin(vZ*6.+uTime*.35+uId*1.7);float mixRB=step(2.5,uId);vec3 c=mix(mix(navy,blue,.38+.24*stripe),mix(red,silver,.20+.18*stripe),mixRB);c+=fres*vec3(.28,.34,.42);float edge=1.-smoothstep(.58,1.,vEdge);float alpha=(.30+fres*.42)*edge*(.78+.22*sin(uScroll*3.14159));outColor=vec4(c,alpha);}`;
function sh(t,s){const o=gl.createShader(t);gl.shaderSource(o,s);gl.compileShader(o);return o}const p=gl.createProgram();gl.attachShader(p,sh(gl.VERTEX_SHADER,VS));gl.attachShader(p,sh(gl.FRAGMENT_SHADER,FS));gl.linkProgram(p);gl.useProgram(p);
const seg=coarse?90:150,verts=[],idx=[];for(let i=0;i<=seg;i++){let u=i/seg;verts.push(u,0,u,1)}for(let i=0;i<seg;i++){let a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,b,c,b,d,c)}const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);const loc=gl.getAttribLocation(p,'aUV');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint32Array(idx),gl.STATIC_DRAW);
function perspective(fov,a,n,f){const k=1/Math.tan(fov/2),nf=1/(n-f);return new Float32Array([k/a,0,0,0,0,k,0,0,0,0,(f+n)*nf,-1,0,0,2*f*n*nf,0])}const view=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,-7.3,1]);const U={proj:gl.getUniformLocation(p,'uProj'),view:gl.getUniformLocation(p,'uView'),time:gl.getUniformLocation(p,'uTime'),scroll:gl.getUniformLocation(p,'uScroll'),id:gl.getUniformLocation(p,'uId'),phase:gl.getUniformLocation(p,'uPhase'),mouse:gl.getUniformLocation(p,'uMouse')};let tx=0,ty=0,mx=0,my=0;if(!coarse)addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2},{passive:true});function resize(){const d=Math.min(devicePixelRatio||1,coarse?1.15:1.55),w=Math.floor(innerWidth*d),h=Math.floor(innerHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';gl.viewport(0,0,w,h)}}gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.enable(gl.DEPTH_TEST);const start=performance.now();function draw(now){resize();mx+=(tx-mx)*.045;my+=(ty-my)*.045;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),scroll=scrollY/max;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.proj,false,perspective(Math.PI/4,canvas.width/canvas.height,.1,30));gl.uniformMatrix4fv(U.view,false,view);gl.uniform1f(U.time,(now-start)/1000);gl.uniform1f(U.scroll,scroll);gl.uniform2f(U.mouse,mx,my);const count=coarse?4:6;for(let i=0;i<count;i++){gl.uniform1f(U.id,i);gl.uniform1f(U.phase,i*1.31);gl.drawElements(gl.TRIANGLES,idx.length,gl.UNSIGNED_INT,0)}requestAnimationFrame(draw)}requestAnimationFrame(draw);
})();