(() => {
  const canvas = document.getElementById('glCanvas');
  const gl = canvas.getContext('webgl2', { alpha: true, antialias: true, premultipliedAlpha: true });
  if (!gl) { canvas.style.display = 'none'; return; }

  const VS = `#version 300 es
  precision highp float;
  in vec2 aUV;
  uniform mat4 uProj; uniform mat4 uView; uniform float uTime; uniform float uScroll; uniform float uPhase; uniform float uId; uniform vec2 uMouse;
  out vec3 vNormal; out float vEdge; out float vDepth;
  mat3 rotX(float a){float c=cos(a),s=sin(a);return mat3(1.,0.,0.,0.,c,-s,0.,s,c);} mat3 rotY(float a){float c=cos(a),s=sin(a);return mat3(c,0.,s,0.,1.,0.,-s,0.,c);} mat3 rotZ(float a){float c=cos(a),s=sin(a);return mat3(c,-s,0.,s,c,0.,0.,0.,1.);}
  vec3 ribbonPoint(vec2 uv){float u=uv.x;float v=uv.y-.5;float chapter=uScroll;float waveAmp=mix(.32,.68,smoothstep(.10,.55,chapter));float x=(u-.5)*7.0;float y=sin(u*5.2+uPhase+uTime*.55)*waveAmp;y+=sin(u*11.0+uPhase*1.7-uTime*.28)*.08;float z=cos(u*3.1+uPhase+uTime*.24)*(.36+.32*sin(chapter*3.14159));float twist=u*7.2+uPhase+uTime*.32+chapter*3.5;float width=.20+.055*sin(u*6.0+uPhase);y+=v*width*cos(twist);z+=v*width*sin(twist);return vec3(x,y,z);}
  void main(){vec3 p=ribbonPoint(aUV);float spread=(uId-2.0)*.34;p.y+=spread;p.z+=(uId-2.0)*.06;float chapter=uScroll;float flower=smoothstep(.30,.58,chapter)*(1.0-smoothstep(.72,.90,chapter));float ang=chapter*2.6+uId*.22+uMouse.x*.28;p=rotY(ang*.42)*rotZ((uId-2.0)*.08+chapter*.08)*p;p=rotX(uMouse.y*.18)*p;p.x*=mix(1.0,.76,flower);p.y*=mix(1.0,1.22,flower);float heroZoom=smoothstep(.0,.25,chapter);p.z+=mix(.0,.55,heroZoom);p.x+=sin(uId*1.7+chapter*4.0)*.10;vec3 pA=ribbonPoint(vec2(min(aUV.x+.006,1.0),aUV.y));vec3 pB=ribbonPoint(vec2(aUV.x,min(aUV.y+.02,1.0)));vec3 n=normalize(cross(pB-p,pA-p));n=rotY(ang*.42)*rotZ((uId-2.0)*.08+chapter*.08)*n;vNormal=normalize(n);vEdge=abs(aUV.y-.5)*2.0;vDepth=p.z;gl_Position=uProj*uView*vec4(p,1.0);}`;

  const FS = `#version 300 es
  precision highp float; in vec3 vNormal; in float vEdge; in float vDepth; uniform float uId; uniform float uScroll; uniform float uTime; out vec4 outColor;
  void main(){vec3 deep=vec3(.035,.18,.19);vec3 teal=vec3(.22,.68,.64);vec3 ivory=vec3(.92,.88,.84);vec3 nude=vec3(.58,.42,.34);float chapter=uScroll;float shine=pow(max(.0,1.0-abs(dot(normalize(vNormal),vec3(0.,0.,1.)))),2.0);float stripe=.5+.5*sin(vDepth*5.0+uTime*.45+uId);vec3 c=mix(deep,teal,.48+.22*stripe);c=mix(c,ivory,smoothstep(.58,.76,chapter)*.18);c=mix(c,nude,smoothstep(.74,.92,chapter)*.10);c+=shine*vec3(.26,.38,.36);float edgeFade=1.0-smoothstep(.58,1.0,vEdge);float alpha=(.50+shine*.28)*edgeFade;outColor=vec4(c,alpha);}`;

  const SVS = `#version 300 es
  precision highp float; in vec3 aPos; in vec3 aNormal; uniform mat4 uProj; uniform mat4 uView; uniform float uTime; uniform float uScroll; uniform float uId; uniform vec2 uMouse; out vec3 vN; out vec3 vP;
  mat3 rotX(float a){float c=cos(a),s=sin(a);return mat3(1.,0.,0.,0.,c,-s,0.,s,c);} mat3 rotY(float a){float c=cos(a),s=sin(a);return mat3(c,0.,s,0.,1.,0.,-s,0.,c);}
  void main(){float show=smoothstep(.36,.46,uScroll)*(1.0-smoothstep(.72,.82,uScroll));float angle=uId*1.047+uTime*.18+uScroll*1.6;float radius=mix(2.35,1.65,smoothstep(.46,.66,uScroll));vec3 center=vec3(cos(angle)*radius,sin(angle*1.1)*.82,sin(angle)*.65);center.x+=(uId-2.5)*.04;float s=(.18+.065*sin(uId*2.1+uTime*.5))*show;vec3 p=aPos*s+center;p=rotY(uMouse.x*.18)*rotX(uMouse.y*.14)*p;vN=normalize(rotY(uMouse.x*.18)*aNormal);vP=p;gl_Position=uProj*uView*vec4(p,1.0);}`;

  const SFS = `#version 300 es
  precision highp float; in vec3 vN; in vec3 vP; uniform float uScroll; uniform float uId; out vec4 outColor;
  void main(){vec3 V=normalize(vec3(0.,0.,1.)-vP);float fres=pow(1.0-max(0.0,dot(normalize(vN),V)),2.4);float light=max(.0,dot(normalize(vN),normalize(vec3(-.4,.7,1.))));vec3 base=mix(vec3(.12,.42,.43),vec3(.36,.86,.82),.45+uId*.06);base=mix(base,vec3(.92,.87,.81),fres*.34);outColor=vec4(base*(.55+.55*light)+fres*.26,.55+.35*fres);}`;

  function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))console.warn(gl.getShaderInfoLog(s));return s;}
  function program(vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))console.warn(gl.getProgramInfoLog(p));return p;}
  const ribbonProgram=program(VS,FS),sphereProgram=program(SVS,SFS);
  function makeRibbon(segments=180){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments;verts.push(u,0,u,1);}for(let i=0;i<segments;i++){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,b,c,b,d,c);}const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);const loc=gl.getAttribLocation(ribbonProgram,'aUV');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint32Array(idx),gl.STATIC_DRAW);gl.bindVertexArray(null);return{vao,count:idx.length};}
  function makeSphere(lat=22,lon=32){const pos=[],norm=[],idx=[];for(let y=0;y<=lat;y++){const v=y/lat,phi=v*Math.PI;for(let x=0;x<=lon;x++){const u=x/lon,th=u*Math.PI*2;const sx=Math.sin(phi)*Math.cos(th),sy=Math.cos(phi),sz=Math.sin(phi)*Math.sin(th);pos.push(sx,sy,sz);norm.push(sx,sy,sz);}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){const a=y*(lon+1)+x,b=a+lon+1;idx.push(a,b,a+1,b,b+1,a+1);}const vao=gl.createVertexArray();gl.bindVertexArray(vao);const pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(pos),gl.STATIC_DRAW);let loc=gl.getAttribLocation(sphereProgram,'aPos');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);const nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(norm),gl.STATIC_DRAW);loc=gl.getAttribLocation(sphereProgram,'aNormal');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint32Array(idx),gl.STATIC_DRAW);gl.bindVertexArray(null);return{vao,count:idx.length};}
  const ribbon=makeRibbon(),sphere=makeSphere();
  function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
  function viewMatrix(z){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,-z,1]);}
  let mx=0,my=0,tmx=0,tmy=0;window.addEventListener('pointermove',e=>{tmx=(e.clientX/innerWidth-.5)*2;tmy=(e.clientY/innerHeight-.5)*2;});
  function resize(){const dpr=Math.min(devicePixelRatio||1,2);const w=Math.floor(innerWidth*dpr),h=Math.floor(innerHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';gl.viewport(0,0,w,h);}}
  function uniform(program,name){return gl.getUniformLocation(program,name)}
  const ru={proj:uniform(ribbonProgram,'uProj'),view:uniform(ribbonProgram,'uView'),time:uniform(ribbonProgram,'uTime'),scroll:uniform(ribbonProgram,'uScroll'),phase:uniform(ribbonProgram,'uPhase'),id:uniform(ribbonProgram,'uId'),mouse:uniform(ribbonProgram,'uMouse')};
  const su={proj:uniform(sphereProgram,'uProj'),view:uniform(sphereProgram,'uView'),time:uniform(sphereProgram,'uTime'),scroll:uniform(sphereProgram,'uScroll'),id:uniform(sphereProgram,'uId'),mouse:uniform(sphereProgram,'uMouse')};
  gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);const start=performance.now();
  function render(now){resize();mx+=(tmx-mx)*.04;my+=(tmy-my)*.04;const time=(now-start)/1000;const max=document.documentElement.scrollHeight-innerHeight;const scroll=max>0?scrollY/max:0;const proj=perspective(Math.PI/4,canvas.width/canvas.height,.1,30);const view=viewMatrix(7.2);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(ribbonProgram);gl.bindVertexArray(ribbon.vao);gl.uniformMatrix4fv(ru.proj,false,proj);gl.uniformMatrix4fv(ru.view,false,view);gl.uniform1f(ru.time,time);gl.uniform1f(ru.scroll,scroll);gl.uniform2f(ru.mouse,mx,my);for(let i=0;i<7;i++){gl.uniform1f(ru.phase,i*1.37);gl.uniform1f(ru.id,i);gl.drawElements(gl.TRIANGLES,ribbon.count,gl.UNSIGNED_INT,0);}gl.useProgram(sphereProgram);gl.bindVertexArray(sphere.vao);gl.uniformMatrix4fv(su.proj,false,proj);gl.uniformMatrix4fv(su.view,false,view);gl.uniform1f(su.time,time);gl.uniform1f(su.scroll,scroll);gl.uniform2f(su.mouse,mx,my);for(let i=0;i<8;i++){gl.uniform1f(su.id,i);gl.drawElements(gl.TRIANGLES,sphere.count,gl.UNSIGNED_INT,0);}gl.bindVertexArray(null);requestAnimationFrame(render);}
  requestAnimationFrame(render);
})();
